python3 performance_large/generate_hf_model_outputs.py --model_id 2 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 5 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 8 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 11 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 14 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 17 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 20 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 23 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 26 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 29 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 32 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 35 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 38 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 41 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 44 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 47 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 50 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 53 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 56 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 59 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 62 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 65 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 68 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 71 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 74 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 77 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 80 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 83 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 86 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 89 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 92 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 95 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 98 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 101 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 104 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 107 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 110 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 113 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 116 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 119 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 122 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 125 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 128 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 131 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 134 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 137 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 140 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 143 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 146 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 149 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 152 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 155 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 158 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 161 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 164 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 167 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 170 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 173 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 176 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 179 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 182 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 185 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 188 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 191 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 194 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 197 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 200 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 203 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 206 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 209 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 212 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 215 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 218 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 221 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 224 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 227 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 230 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 233 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 236 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 239 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 242 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 245 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 248 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 251 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 254 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 257 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 260 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 263 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 266 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 269 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 272 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 275 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 278 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 281 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 284 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 287 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 290 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 293 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 296 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 299 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 302 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 305 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 308 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 311 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 314 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 317 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 320 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 323 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 326 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 329 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 332 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 335 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 338 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 341 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 344 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 347 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 350 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 353 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 356 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 359 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 362 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 365 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 368 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 371 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 374 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 377 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 380 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 383 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 386 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 389 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 392 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 395 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 398 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 401 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 404 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 407 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 410 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 413 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 416 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 419 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 422 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 425 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 428 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 431 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 434 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 437 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 440 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 443 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 446 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 449 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 452 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 455 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 458 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 461 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 464 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 467 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 470 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 473 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 476 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 479 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 482 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 485 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 488 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 491 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 494 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 497 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 500 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 503 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 506 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 509 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 512 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 515 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 518 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 521 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 524 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 527 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 530 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 533 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 536 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 539 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 542 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 545 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 548 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 551 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 554 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 557 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 560 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 563 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 566 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 569 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 572 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 575 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 578 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 581 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 584 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 587 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 590 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 593 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 596 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 599 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 602 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 605 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 608 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 611 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 614 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 617 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 620 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 623 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 626 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 629 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 632 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 635 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 638 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 641 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 644 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 647 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 650 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 653 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 656 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 659 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 662 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 665 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 668 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 671 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 674 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 677 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 680 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 683 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 686 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 689 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 692 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 695 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 698 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 701 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 704 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 707 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 710 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 713 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 716 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 719 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 722 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 725 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 728 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 731 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 734 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 737 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 740 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 743 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 746 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 749 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 752 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 755 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 758 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 761 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 764 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 767 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 770 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 773 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 776 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 779 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 782 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 785 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 788 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 791 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 794 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 797 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 800 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 803 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 806 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 809 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 812 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 815 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 818 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 821 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 824 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 827 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 830 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 833 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 836 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 839 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 842 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 845 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 848 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 851 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 854 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 857 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 860 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 863 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 866 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 869 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 872 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 875 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 878 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 881 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 884 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 887 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 890 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 893 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 896 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 899 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 902 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 905 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 908 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 911 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 914 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 917 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 920 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 923 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 926 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 929 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 932 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 935 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 938 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 941 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 944 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 947 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 950 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 953 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 956 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 959 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 962 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 965 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 968 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 971 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 974 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 977 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 980 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 983 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 986 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 989 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 992 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 995 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 998 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1001 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1004 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1007 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1010 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1013 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1016 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1019 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1022 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1025 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1028 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1031 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1034 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1037 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1040 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1043 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1046 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1049 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1052 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1055 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1058 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1061 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1064 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1067 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1070 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1073 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1076 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1079 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1082 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1085 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1088 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1091 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1094 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1097 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1100 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1103 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1106 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1109 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1112 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1115 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1118 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1121 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1124 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1127 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1130 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1133 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1136 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1139 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1142 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1145 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1148 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1151 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1154 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1157 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1160 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1163 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1166 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1169 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1172 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1175 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1178 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1181 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1184 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1187 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1190 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1193 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1196 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1199 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1202 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1205 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1208 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1211 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1214 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1217 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1220 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1223 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1226 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1229 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1232 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1235 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1238 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1241 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1244 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1247 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1250 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1253 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1256 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1259 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1262 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1265 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1268 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1271 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1274 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1277 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1280 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1283 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1286 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1289 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1292 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1295 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1298 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1301 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1304 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1307 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1310 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1313 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1316 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1319 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1322 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1325 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1328 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1331 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1334 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1337 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1340 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1343 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1346 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1349 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1352 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1355 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1358 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1361 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1364 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1367 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1370 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1373 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1376 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1379 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1382 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1385 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1388 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1391 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1394 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1397 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1400 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1403 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1406 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1409 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1412 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1415 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1418 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1421 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1424 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1427 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1430 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1433 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1436 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1439 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1442 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1445 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1448 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1451 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1454 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1457 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1460 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1463 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1466 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1469 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1472 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1475 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1478 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1481 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1484 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1487 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1490 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1493 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1496 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1499 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1502 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1505 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1508 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1511 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1514 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1517 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1520 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1523 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1526 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1529 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1532 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1535 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1538 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1541 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1544 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1547 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1550 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1553 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1556 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1559 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1562 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1565 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1568 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1571 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1574 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1577 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1580 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1583 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1586 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1589 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1592 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1595 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1598 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1601 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1604 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1607 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1610 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1613 --device cuda:2