python3 performance_large/generate_full_hf_model_outputs.py --model_id 3 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 9 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 15 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 21 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 27 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 33 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 39 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 45 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 51 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 57 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 63 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 69 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 75 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 81 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 87 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 93 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 99 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 105 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 111 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 117 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 123 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 129 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 135 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 141 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 147 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 153 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 159 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 165 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 171 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 177 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 183 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 189 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 195 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 201 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 207 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 213 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 219 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 225 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 231 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 237 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 243 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 249 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 255 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 261 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 267 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 273 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 279 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 285 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 291 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 297 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 303 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 309 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 315 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 321 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 327 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 333 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 339 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 345 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 351 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 357 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 363 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 369 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 375 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 381 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 387 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 393 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 399 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 405 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 411 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 417 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 423 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 429 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 435 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 441 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 447 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 453 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 459 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 465 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 471 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 477 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 483 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 489 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 495 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 501 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 507 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 513 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 519 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 525 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 531 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 537 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 543 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 549 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 555 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 561 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 567 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 573 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 579 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 585 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 591 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 597 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 603 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 609 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 615 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 621 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 627 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 633 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 639 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 645 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 651 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 657 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 663 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 669 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 675 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 681 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 687 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 693 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 699 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 705 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 711 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 717 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 723 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 729 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 735 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 741 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 747 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 753 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 759 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 765 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 771 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 777 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 783 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 789 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 795 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 801 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 807 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 813 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 819 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 825 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 831 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 837 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 843 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 849 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 855 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 861 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 867 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 873 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 879 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 885 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 891 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 897 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 903 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 909 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 915 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 921 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 927 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 933 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 939 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 945 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 951 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 957 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 963 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 969 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 975 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 981 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 987 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 993 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 999 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1005 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1011 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1017 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1023 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1029 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1035 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1041 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1047 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1053 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1059 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1065 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1071 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1077 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1083 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1089 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1095 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1101 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1107 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1113 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1119 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1125 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1131 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1137 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1143 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1149 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1155 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1161 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1167 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1173 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1179 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1185 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1191 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1197 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1203 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1209 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1215 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1221 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1227 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1233 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1239 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1245 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1251 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1257 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1263 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1269 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1275 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1281 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1287 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1293 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1299 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1305 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1311 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1317 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1323 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1329 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1335 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1341 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1347 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1353 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1359 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1365 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1371 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1377 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1383 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1389 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1395 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1401 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1407 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1413 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1419 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1425 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1431 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1437 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1443 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1449 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1455 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1461 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1467 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1473 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1479 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1485 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1491 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1497 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1503 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1509 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1515 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1521 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1527 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1533 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1539 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1545 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1551 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1557 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1563 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1569 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1575 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1581 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1587 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1593 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1599 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1605 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1611 --device cuda:1