python3 performance_large/generate_hf_model_outputs.py --model_id 1 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 4 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 7 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 10 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 13 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 16 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 19 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 22 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 25 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 28 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 31 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 34 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 37 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 40 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 43 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 46 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 49 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 52 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 55 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 58 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 61 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 64 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 67 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 70 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 73 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 76 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 79 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 82 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 85 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 88 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 91 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 94 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 97 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 100 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 103 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 106 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 109 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 112 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 115 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 118 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 121 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 124 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 127 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 130 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 133 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 136 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 139 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 142 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 145 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 148 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 151 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 154 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 157 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 160 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 163 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 166 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 169 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 172 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 175 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 178 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 181 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 184 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 187 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 190 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 193 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 196 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 199 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 202 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 205 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 208 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 211 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 214 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 217 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 220 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 223 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 226 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 229 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 232 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 235 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 238 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 241 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 244 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 247 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 250 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 253 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 256 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 259 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 262 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 265 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 268 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 271 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 274 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 277 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 280 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 283 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 286 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 289 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 292 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 295 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 298 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 301 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 304 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 307 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 310 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 313 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 316 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 319 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 322 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 325 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 328 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 331 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 334 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 337 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 340 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 343 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 346 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 349 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 352 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 355 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 358 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 361 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 364 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 367 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 370 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 373 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 376 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 379 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 382 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 385 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 388 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 391 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 394 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 397 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 400 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 403 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 406 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 409 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 412 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 415 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 418 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 421 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 424 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 427 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 430 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 433 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 436 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 439 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 442 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 445 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 448 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 451 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 454 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 457 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 460 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 463 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 466 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 469 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 472 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 475 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 478 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 481 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 484 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 487 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 490 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 493 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 496 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 499 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 502 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 505 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 508 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 511 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 514 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 517 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 520 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 523 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 526 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 529 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 532 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 535 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 538 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 541 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 544 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 547 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 550 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 553 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 556 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 559 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 562 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 565 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 568 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 571 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 574 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 577 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 580 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 583 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 586 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 589 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 592 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 595 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 598 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 601 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 604 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 607 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 610 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 613 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 616 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 619 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 622 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 625 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 628 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 631 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 634 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 637 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 640 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 643 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 646 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 649 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 652 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 655 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 658 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 661 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 664 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 667 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 670 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 673 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 676 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 679 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 682 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 685 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 688 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 691 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 694 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 697 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 700 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 703 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 706 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 709 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 712 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 715 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 718 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 721 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 724 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 727 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 730 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 733 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 736 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 739 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 742 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 745 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 748 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 751 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 754 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 757 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 760 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 763 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 766 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 769 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 772 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 775 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 778 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 781 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 784 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 787 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 790 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 793 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 796 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 799 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 802 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 805 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 808 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 811 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 814 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 817 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 820 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 823 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 826 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 829 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 832 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 835 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 838 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 841 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 844 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 847 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 850 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 853 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 856 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 859 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 862 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 865 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 868 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 871 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 874 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 877 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 880 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 883 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 886 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 889 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 892 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 895 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 898 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 901 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 904 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 907 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 910 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 913 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 916 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 919 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 922 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 925 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 928 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 931 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 934 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 937 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 940 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 943 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 946 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 949 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 952 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 955 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 958 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 961 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 964 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 967 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 970 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 973 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 976 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 979 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 982 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 985 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 988 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 991 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 994 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 997 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1000 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1003 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1006 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1009 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1012 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1015 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1018 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1021 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1024 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1027 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1030 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1033 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1036 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1039 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1042 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1045 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1048 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1051 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1054 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1057 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1060 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1063 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1066 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1069 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1072 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1075 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1078 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1081 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1084 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1087 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1090 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1093 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1096 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1099 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1102 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1105 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1108 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1111 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1114 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1117 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1120 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1123 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1126 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1129 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1132 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1135 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1138 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1141 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1144 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1147 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1150 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1153 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1156 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1159 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1162 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1165 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1168 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1171 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1174 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1177 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1180 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1183 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1186 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1189 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1192 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1195 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1198 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1201 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1204 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1207 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1210 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1213 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1216 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1219 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1222 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1225 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1228 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1231 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1234 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1237 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1240 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1243 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1246 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1249 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1252 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1255 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1258 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1261 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1264 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1267 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1270 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1273 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1276 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1279 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1282 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1285 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1288 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1291 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1294 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1297 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1300 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1303 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1306 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1309 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1312 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1315 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1318 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1321 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1324 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1327 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1330 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1333 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1336 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1339 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1342 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1345 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1348 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1351 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1354 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1357 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1360 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1363 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1366 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1369 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1372 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1375 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1378 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1381 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1384 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1387 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1390 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1393 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1396 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1399 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1402 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1405 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1408 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1411 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1414 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1417 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1420 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1423 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1426 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1429 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1432 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1435 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1438 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1441 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1444 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1447 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1450 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1453 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1456 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1459 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1462 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1465 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1468 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1471 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1474 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1477 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1480 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1483 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1486 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1489 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1492 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1495 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1498 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1501 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1504 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1507 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1510 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1513 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1516 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1519 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1522 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1525 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1528 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1531 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1534 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1537 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1540 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1543 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1546 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1549 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1552 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1555 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1558 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1561 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1564 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1567 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1570 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1573 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1576 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1579 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1582 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1585 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1588 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1591 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1594 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1597 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1600 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1603 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1606 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1609 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1612 --device cuda:1