python3 performance_large/generate_hf_model_outputs.py --model_id 8 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 20 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 32 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 44 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 56 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 68 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 80 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 92 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 104 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 116 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 128 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 140 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 152 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 164 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 176 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 188 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 200 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 212 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 224 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 236 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 248 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 260 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 272 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 284 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 296 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 308 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 320 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 332 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 344 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 356 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 368 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 380 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 392 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 404 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 416 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 428 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 440 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 452 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 464 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 476 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 488 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 500 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 512 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 524 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 536 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 548 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 560 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 572 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 584 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 596 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 608 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 620 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 632 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 644 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 656 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 668 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 680 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 692 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 704 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 716 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 728 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 740 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 752 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 764 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 776 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 788 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 800 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 812 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 824 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 836 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 848 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 860 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 872 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 884 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 896 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 908 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 920 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 932 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 944 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 956 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 968 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 980 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 992 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1004 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1016 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1028 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1040 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1052 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1064 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1076 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1088 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1100 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1112 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1124 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1136 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1148 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1160 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1172 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1184 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1196 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1208 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1220 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1232 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1244 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1256 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1268 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1280 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1292 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1304 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1316 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1328 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1340 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1352 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1364 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1376 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1388 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1400 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1412 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1424 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1436 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1448 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1460 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1472 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1484 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1496 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1508 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1520 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1532 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1544 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1556 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1568 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1580 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1592 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1604 --device cuda:2