python3 performance_large/generate_hf_model_outputs.py --model_id 0 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 3 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 6 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 9 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 12 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 15 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 18 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 21 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 24 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 27 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 30 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 33 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 36 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 39 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 42 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 45 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 48 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 51 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 54 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 57 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 60 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 63 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 66 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 69 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 72 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 75 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 78 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 81 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 84 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 87 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 90 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 93 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 96 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 99 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 102 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 105 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 108 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 111 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 114 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 117 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 120 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 123 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 126 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 129 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 132 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 135 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 138 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 141 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 144 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 147 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 150 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 153 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 156 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 159 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 162 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 165 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 168 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 171 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 174 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 177 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 180 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 183 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 186 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 189 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 192 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 195 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 198 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 201 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 204 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 207 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 210 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 213 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 216 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 219 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 222 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 225 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 228 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 231 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 234 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 237 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 240 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 243 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 246 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 249 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 252 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 255 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 258 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 261 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 264 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 267 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 270 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 273 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 276 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 279 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 282 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 285 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 288 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 291 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 294 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 297 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 300 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 303 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 306 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 309 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 312 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 315 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 318 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 321 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 324 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 327 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 330 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 333 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 336 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 339 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 342 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 345 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 348 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 351 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 354 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 357 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 360 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 363 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 366 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 369 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 372 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 375 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 378 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 381 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 384 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 387 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 390 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 393 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 396 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 399 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 402 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 405 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 408 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 411 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 414 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 417 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 420 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 423 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 426 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 429 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 432 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 435 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 438 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 441 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 444 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 447 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 450 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 453 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 456 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 459 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 462 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 465 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 468 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 471 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 474 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 477 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 480 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 483 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 486 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 489 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 492 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 495 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 498 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 501 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 504 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 507 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 510 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 513 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 516 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 519 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 522 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 525 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 528 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 531 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 534 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 537 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 540 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 543 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 546 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 549 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 552 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 555 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 558 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 561 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 564 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 567 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 570 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 573 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 576 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 579 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 582 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 585 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 588 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 591 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 594 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 597 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 600 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 603 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 606 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 609 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 612 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 615 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 618 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 621 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 624 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 627 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 630 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 633 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 636 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 639 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 642 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 645 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 648 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 651 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 654 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 657 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 660 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 663 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 666 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 669 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 672 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 675 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 678 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 681 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 684 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 687 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 690 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 693 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 696 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 699 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 702 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 705 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 708 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 711 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 714 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 717 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 720 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 723 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 726 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 729 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 732 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 735 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 738 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 741 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 744 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 747 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 750 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 753 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 756 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 759 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 762 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 765 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 768 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 771 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 774 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 777 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 780 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 783 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 786 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 789 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 792 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 795 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 798 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 801 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 804 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 807 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 810 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 813 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 816 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 819 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 822 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 825 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 828 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 831 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 834 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 837 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 840 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 843 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 846 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 849 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 852 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 855 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 858 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 861 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 864 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 867 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 870 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 873 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 876 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 879 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 882 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 885 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 888 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 891 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 894 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 897 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 900 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 903 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 906 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 909 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 912 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 915 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 918 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 921 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 924 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 927 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 930 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 933 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 936 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 939 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 942 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 945 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 948 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 951 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 954 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 957 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 960 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 963 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 966 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 969 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 972 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 975 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 978 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 981 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 984 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 987 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 990 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 993 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 996 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 999 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1002 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1005 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1008 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1011 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1014 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1017 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1020 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1023 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1026 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1029 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1032 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1035 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1038 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1041 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1044 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1047 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1050 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1053 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1056 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1059 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1062 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1065 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1068 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1071 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1074 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1077 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1080 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1083 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1086 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1089 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1092 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1095 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1098 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1101 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1104 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1107 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1110 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1113 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1116 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1119 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1122 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1125 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1128 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1131 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1134 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1137 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1140 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1143 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1146 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1149 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1152 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1155 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1158 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1161 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1164 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1167 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1170 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1173 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1176 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1179 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1182 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1185 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1188 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1191 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1194 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1197 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1200 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1203 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1206 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1209 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1212 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1215 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1218 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1221 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1224 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1227 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1230 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1233 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1236 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1239 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1242 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1245 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1248 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1251 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1254 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1257 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1260 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1263 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1266 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1269 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1272 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1275 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1278 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1281 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1284 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1287 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1290 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1293 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1296 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1299 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1302 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1305 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1308 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1311 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1314 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1317 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1320 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1323 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1326 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1329 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1332 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1335 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1338 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1341 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1344 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1347 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1350 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1353 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1356 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1359 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1362 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1365 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1368 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1371 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1374 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1377 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1380 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1383 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1386 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1389 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1392 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1395 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1398 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1401 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1404 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1407 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1410 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1413 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1416 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1419 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1422 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1425 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1428 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1431 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1434 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1437 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1440 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1443 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1446 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1449 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1452 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1455 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1458 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1461 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1464 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1467 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1470 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1473 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1476 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1479 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1482 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1485 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1488 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1491 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1494 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1497 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1500 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1503 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1506 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1509 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1512 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1515 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1518 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1521 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1524 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1527 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1530 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1533 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1536 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1539 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1542 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1545 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1548 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1551 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1554 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1557 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1560 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1563 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1566 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1569 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1572 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1575 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1578 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1581 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1584 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1587 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1590 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1593 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1596 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1599 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1602 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1605 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1608 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1611 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1614 --device cuda:0