python3 performance_large/generate_hf_model_outputs.py --model_id 2 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 14 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 26 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 38 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 50 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 62 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 74 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 86 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 98 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 110 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 122 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 134 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 146 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 158 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 170 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 182 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 194 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 206 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 218 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 230 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 242 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 254 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 266 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 278 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 290 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 302 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 314 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 326 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 338 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 350 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 362 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 374 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 386 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 398 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 410 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 422 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 434 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 446 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 458 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 470 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 482 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 494 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 506 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 518 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 530 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 542 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 554 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 566 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 578 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 590 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 602 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 614 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 626 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 638 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 650 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 662 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 674 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 686 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 698 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 710 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 722 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 734 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 746 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 758 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 770 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 782 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 794 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 806 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 818 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 830 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 842 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 854 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 866 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 878 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 890 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 902 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 914 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 926 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 938 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 950 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 962 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 974 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 986 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 998 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1010 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1022 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1034 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1046 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1058 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1070 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1082 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1094 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1106 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1118 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1130 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1142 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1154 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1166 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1178 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1190 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1202 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1214 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1226 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1238 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1250 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1262 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1274 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1286 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1298 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1310 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1322 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1334 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1346 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1358 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1370 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1382 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1394 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1406 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1418 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1430 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1442 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1454 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1466 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1478 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1490 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1502 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1514 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1526 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1538 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1550 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1562 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1574 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1586 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1598 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1610 --device cuda:0