python3 performance_large/generate_hf_model_outputs.py --model_id 1 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 13 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 25 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 37 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 49 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 61 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 73 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 85 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 97 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 109 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 121 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 133 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 145 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 157 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 169 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 181 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 193 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 205 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 217 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 229 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 241 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 253 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 265 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 277 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 289 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 301 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 313 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 325 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 337 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 349 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 361 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 373 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 385 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 397 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 409 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 421 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 433 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 445 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 457 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 469 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 481 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 493 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 505 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 517 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 529 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 541 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 553 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 565 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 577 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 589 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 601 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 613 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 625 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 637 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 649 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 661 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 673 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 685 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 697 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 709 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 721 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 733 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 745 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 757 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 769 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 781 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 793 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 805 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 817 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 829 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 841 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 853 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 865 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 877 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 889 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 901 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 913 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 925 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 937 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 949 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 961 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 973 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 985 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 997 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1009 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1021 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1033 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1045 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1057 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1069 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1081 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1093 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1105 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1117 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1129 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1141 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1153 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1165 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1177 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1189 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1201 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1213 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1225 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1237 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1249 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1261 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1273 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1285 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1297 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1309 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1321 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1333 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1345 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1357 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1369 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1381 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1393 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1405 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1417 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1429 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1441 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1453 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1465 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1477 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1489 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1501 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1513 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1525 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1537 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1549 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1561 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1573 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1585 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1597 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1609 --device cuda:0