python3 performance_large/generate_hf_model_outputs.py --model_id 4 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 16 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 28 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 40 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 52 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 64 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 76 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 88 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 100 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 112 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 124 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 136 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 148 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 160 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 172 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 184 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 196 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 208 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 220 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 232 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 244 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 256 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 268 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 280 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 292 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 304 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 316 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 328 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 340 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 352 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 364 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 376 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 388 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 400 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 412 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 424 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 436 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 448 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 460 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 472 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 484 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 496 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 508 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 520 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 532 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 544 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 556 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 568 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 580 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 592 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 604 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 616 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 628 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 640 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 652 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 664 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 676 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 688 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 700 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 712 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 724 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 736 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 748 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 760 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 772 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 784 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 796 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 808 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 820 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 832 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 844 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 856 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 868 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 880 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 892 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 904 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 916 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 928 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 940 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 952 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 964 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 976 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 988 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1000 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1012 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1024 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1036 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1048 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1060 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1072 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1084 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1096 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1108 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1120 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1132 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1144 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1156 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1168 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1180 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1192 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1204 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1216 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1228 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1240 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1252 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1264 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1276 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1288 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1300 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1312 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1324 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1336 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1348 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1360 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1372 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1384 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1396 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1408 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1420 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1432 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1444 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1456 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1468 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1480 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1492 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1504 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1516 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1528 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1540 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1552 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1564 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1576 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1588 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1600 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1612 --device cuda:1