python3 performance_large/generate_hf_model_outputs.py --model_id 3 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 15 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 27 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 39 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 51 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 63 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 75 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 87 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 99 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 111 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 123 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 135 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 147 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 159 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 171 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 183 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 195 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 207 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 219 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 231 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 243 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 255 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 267 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 279 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 291 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 303 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 315 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 327 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 339 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 351 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 363 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 375 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 387 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 399 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 411 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 423 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 435 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 447 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 459 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 471 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 483 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 495 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 507 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 519 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 531 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 543 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 555 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 567 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 579 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 591 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 603 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 615 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 627 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 639 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 651 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 663 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 675 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 687 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 699 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 711 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 723 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 735 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 747 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 759 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 771 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 783 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 795 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 807 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 819 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 831 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 843 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 855 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 867 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 879 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 891 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 903 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 915 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 927 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 939 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 951 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 963 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 975 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 987 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 999 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1011 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1023 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1035 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1047 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1059 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1071 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1083 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1095 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1107 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1119 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1131 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1143 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1155 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1167 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1179 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1191 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1203 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1215 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1227 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1239 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1251 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1263 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1275 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1287 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1299 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1311 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1323 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1335 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1347 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1359 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1371 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1383 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1395 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1407 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1419 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1431 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1443 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1455 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1467 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1479 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1491 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1503 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1515 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1527 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1539 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1551 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1563 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1575 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1587 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1599 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1611 --device cuda:0