python3 performance_large/generate_hf_model_outputs.py --model_id 11 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 23 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 35 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 47 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 59 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 71 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 83 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 95 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 107 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 119 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 131 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 143 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 155 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 167 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 179 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 191 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 203 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 215 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 227 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 239 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 251 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 263 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 275 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 287 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 299 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 311 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 323 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 335 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 347 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 359 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 371 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 383 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 395 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 407 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 419 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 431 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 443 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 455 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 467 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 479 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 491 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 503 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 515 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 527 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 539 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 551 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 563 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 575 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 587 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 599 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 611 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 623 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 635 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 647 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 659 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 671 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 683 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 695 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 707 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 719 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 731 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 743 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 755 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 767 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 779 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 791 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 803 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 815 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 827 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 839 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 851 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 863 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 875 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 887 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 899 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 911 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 923 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 935 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 947 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 959 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 971 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 983 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 995 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1007 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1019 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1031 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1043 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1055 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1067 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1079 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1091 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1103 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1115 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1127 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1139 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1151 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1163 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1175 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1187 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1199 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1211 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1223 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1235 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1247 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1259 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1271 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1283 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1295 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1307 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1319 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1331 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1343 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1355 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1367 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1379 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1391 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1403 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1415 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1427 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1439 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1451 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1463 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1475 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1487 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1499 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1511 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1523 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1535 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1547 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1559 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1571 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1583 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1595 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1607 --device cuda:2