python3 performance_large/generate_full_hf_model_outputs.py --model_id 1 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 7 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 13 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 19 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 25 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 31 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 37 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 43 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 49 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 55 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 61 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 67 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 73 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 79 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 85 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 91 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 97 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 103 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 109 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 115 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 121 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 127 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 133 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 139 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 145 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 151 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 157 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 163 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 169 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 175 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 181 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 187 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 193 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 199 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 205 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 211 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 217 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 223 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 229 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 235 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 241 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 247 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 253 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 259 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 265 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 271 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 277 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 283 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 289 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 295 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 301 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 307 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 313 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 319 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 325 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 331 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 337 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 343 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 349 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 355 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 361 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 367 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 373 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 379 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 385 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 391 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 397 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 403 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 409 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 415 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 421 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 427 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 433 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 439 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 445 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 451 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 457 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 463 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 469 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 475 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 481 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 487 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 493 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 499 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 505 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 511 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 517 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 523 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 529 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 535 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 541 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 547 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 553 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 559 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 565 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 571 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 577 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 583 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 589 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 595 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 601 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 607 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 613 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 619 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 625 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 631 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 637 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 643 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 649 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 655 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 661 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 667 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 673 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 679 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 685 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 691 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 697 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 703 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 709 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 715 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 721 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 727 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 733 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 739 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 745 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 751 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 757 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 763 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 769 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 775 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 781 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 787 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 793 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 799 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 805 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 811 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 817 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 823 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 829 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 835 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 841 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 847 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 853 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 859 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 865 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 871 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 877 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 883 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 889 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 895 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 901 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 907 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 913 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 919 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 925 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 931 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 937 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 943 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 949 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 955 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 961 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 967 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 973 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 979 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 985 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 991 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 997 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1003 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1009 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1015 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1021 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1027 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1033 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1039 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1045 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1051 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1057 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1063 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1069 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1075 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1081 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1087 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1093 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1099 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1105 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1111 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1117 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1123 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1129 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1135 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1141 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1147 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1153 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1159 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1165 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1171 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1177 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1183 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1189 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1195 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1201 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1207 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1213 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1219 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1225 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1231 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1237 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1243 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1249 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1255 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1261 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1267 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1273 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1279 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1285 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1291 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1297 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1303 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1309 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1315 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1321 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1327 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1333 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1339 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1345 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1351 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1357 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1363 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1369 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1375 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1381 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1387 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1393 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1399 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1405 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1411 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1417 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1423 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1429 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1435 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1441 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1447 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1453 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1459 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1465 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1471 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1477 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1483 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1489 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1495 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1501 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1507 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1513 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1519 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1525 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1531 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1537 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1543 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1549 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1555 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1561 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1567 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1573 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1579 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1585 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1591 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1597 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1603 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1609 --device cuda:0