python3 performance_large/generate_full_hf_model_outputs.py --model_id 2 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 8 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 14 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 20 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 26 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 32 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 38 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 44 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 50 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 56 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 62 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 68 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 74 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 80 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 86 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 92 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 98 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 104 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 110 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 116 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 122 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 128 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 134 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 140 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 146 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 152 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 158 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 164 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 170 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 176 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 182 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 188 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 194 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 200 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 206 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 212 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 218 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 224 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 230 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 236 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 242 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 248 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 254 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 260 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 266 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 272 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 278 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 284 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 290 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 296 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 302 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 308 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 314 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 320 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 326 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 332 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 338 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 344 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 350 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 356 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 362 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 368 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 374 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 380 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 386 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 392 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 398 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 404 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 410 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 416 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 422 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 428 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 434 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 440 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 446 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 452 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 458 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 464 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 470 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 476 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 482 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 488 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 494 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 500 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 506 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 512 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 518 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 524 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 530 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 536 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 542 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 548 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 554 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 560 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 566 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 572 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 578 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 584 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 590 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 596 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 602 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 608 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 614 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 620 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 626 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 632 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 638 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 644 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 650 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 656 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 662 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 668 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 674 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 680 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 686 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 692 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 698 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 704 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 710 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 716 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 722 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 728 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 734 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 740 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 746 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 752 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 758 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 764 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 770 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 776 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 782 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 788 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 794 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 800 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 806 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 812 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 818 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 824 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 830 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 836 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 842 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 848 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 854 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 860 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 866 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 872 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 878 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 884 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 890 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 896 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 902 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 908 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 914 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 920 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 926 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 932 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 938 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 944 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 950 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 956 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 962 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 968 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 974 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 980 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 986 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 992 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 998 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1004 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1010 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1016 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1022 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1028 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1034 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1040 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1046 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1052 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1058 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1064 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1070 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1076 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1082 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1088 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1094 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1100 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1106 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1112 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1118 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1124 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1130 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1136 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1142 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1148 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1154 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1160 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1166 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1172 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1178 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1184 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1190 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1196 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1202 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1208 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1214 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1220 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1226 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1232 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1238 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1244 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1250 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1256 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1262 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1268 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1274 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1280 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1286 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1292 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1298 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1304 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1310 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1316 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1322 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1328 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1334 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1340 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1346 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1352 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1358 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1364 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1370 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1376 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1382 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1388 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1394 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1400 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1406 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1412 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1418 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1424 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1430 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1436 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1442 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1448 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1454 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1460 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1466 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1472 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1478 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1484 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1490 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1496 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1502 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1508 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1514 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1520 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1526 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1532 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1538 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1544 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1550 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1556 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1562 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1568 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1574 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1580 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1586 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1592 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1598 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1604 --device cuda:1
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1610 --device cuda:1