python3 performance_large/generate_hf_model_outputs.py --model_id 7 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 19 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 31 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 43 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 55 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 67 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 79 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 91 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 103 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 115 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 127 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 139 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 151 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 163 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 175 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 187 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 199 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 211 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 223 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 235 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 247 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 259 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 271 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 283 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 295 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 307 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 319 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 331 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 343 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 355 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 367 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 379 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 391 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 403 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 415 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 427 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 439 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 451 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 463 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 475 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 487 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 499 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 511 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 523 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 535 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 547 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 559 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 571 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 583 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 595 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 607 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 619 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 631 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 643 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 655 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 667 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 679 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 691 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 703 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 715 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 727 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 739 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 751 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 763 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 775 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 787 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 799 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 811 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 823 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 835 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 847 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 859 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 871 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 883 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 895 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 907 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 919 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 931 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 943 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 955 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 967 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 979 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 991 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1003 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1015 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1027 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1039 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1051 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1063 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1075 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1087 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1099 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1111 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1123 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1135 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1147 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1159 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1171 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1183 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1195 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1207 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1219 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1231 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1243 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1255 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1267 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1279 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1291 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1303 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1315 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1327 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1339 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1351 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1363 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1375 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1387 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1399 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1411 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1423 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1435 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1447 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1459 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1471 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1483 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1495 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1507 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1519 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1531 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1543 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1555 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1567 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1579 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1591 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1603 --device cuda:1