python3 performance_large/generate_hf_model_outputs.py --model_id 10 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 22 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 34 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 46 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 58 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 70 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 82 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 94 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 106 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 118 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 130 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 142 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 154 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 166 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 178 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 190 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 202 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 214 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 226 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 238 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 250 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 262 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 274 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 286 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 298 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 310 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 322 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 334 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 346 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 358 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 370 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 382 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 394 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 406 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 418 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 430 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 442 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 454 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 466 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 478 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 490 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 502 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 514 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 526 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 538 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 550 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 562 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 574 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 586 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 598 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 610 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 622 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 634 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 646 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 658 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 670 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 682 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 694 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 706 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 718 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 730 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 742 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 754 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 766 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 778 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 790 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 802 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 814 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 826 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 838 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 850 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 862 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 874 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 886 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 898 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 910 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 922 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 934 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 946 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 958 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 970 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 982 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 994 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1006 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1018 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1030 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1042 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1054 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1066 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1078 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1090 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1102 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1114 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1126 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1138 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1150 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1162 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1174 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1186 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1198 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1210 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1222 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1234 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1246 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1258 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1270 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1282 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1294 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1306 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1318 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1330 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1342 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1354 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1366 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1378 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1390 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1402 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1414 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1426 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1438 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1450 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1462 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1474 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1486 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1498 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1510 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1522 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1534 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1546 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1558 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1570 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1582 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1594 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1606 --device cuda:2