python3 performance_large/generate_hf_model_outputs.py --model_id 0 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 12 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 24 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 36 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 48 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 60 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 72 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 84 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 96 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 108 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 120 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 132 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 144 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 156 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 168 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 180 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 192 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 204 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 216 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 228 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 240 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 252 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 264 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 276 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 288 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 300 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 312 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 324 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 336 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 348 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 360 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 372 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 384 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 396 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 408 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 420 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 432 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 444 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 456 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 468 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 480 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 492 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 504 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 516 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 528 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 540 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 552 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 564 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 576 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 588 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 600 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 612 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 624 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 636 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 648 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 660 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 672 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 684 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 696 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 708 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 720 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 732 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 744 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 756 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 768 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 780 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 792 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 804 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 816 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 828 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 840 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 852 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 864 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 876 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 888 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 900 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 912 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 924 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 936 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 948 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 960 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 972 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 984 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 996 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1008 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1020 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1032 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1044 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1056 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1068 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1080 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1092 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1104 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1116 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1128 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1140 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1152 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1164 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1176 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1188 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1200 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1212 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1224 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1236 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1248 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1260 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1272 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1284 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1296 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1308 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1320 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1332 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1344 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1356 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1368 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1380 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1392 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1404 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1416 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1428 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1440 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1452 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1464 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1476 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1488 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1500 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1512 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1524 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1536 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1548 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1560 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1572 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1584 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1596 --device cuda:0
python3 performance_large/generate_hf_model_outputs.py --model_id 1608 --device cuda:0