python3 performance_large/generate_full_hf_model_outputs.py --model_id 0 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 6 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 12 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 18 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 24 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 30 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 36 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 42 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 48 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 54 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 60 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 66 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 72 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 78 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 84 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 90 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 96 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 102 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 108 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 114 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 120 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 126 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 132 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 138 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 144 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 150 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 156 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 162 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 168 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 174 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 180 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 186 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 192 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 198 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 204 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 210 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 216 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 222 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 228 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 234 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 240 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 246 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 252 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 258 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 264 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 270 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 276 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 282 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 288 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 294 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 300 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 306 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 312 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 318 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 324 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 330 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 336 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 342 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 348 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 354 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 360 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 366 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 372 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 378 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 384 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 390 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 396 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 402 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 408 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 414 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 420 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 426 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 432 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 438 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 444 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 450 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 456 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 462 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 468 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 474 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 480 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 486 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 492 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 498 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 504 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 510 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 516 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 522 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 528 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 534 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 540 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 546 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 552 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 558 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 564 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 570 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 576 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 582 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 588 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 594 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 600 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 606 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 612 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 618 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 624 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 630 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 636 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 642 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 648 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 654 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 660 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 666 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 672 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 678 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 684 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 690 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 696 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 702 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 708 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 714 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 720 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 726 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 732 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 738 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 744 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 750 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 756 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 762 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 768 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 774 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 780 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 786 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 792 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 798 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 804 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 810 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 816 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 822 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 828 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 834 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 840 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 846 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 852 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 858 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 864 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 870 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 876 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 882 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 888 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 894 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 900 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 906 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 912 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 918 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 924 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 930 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 936 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 942 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 948 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 954 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 960 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 966 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 972 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 978 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 984 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 990 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 996 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1002 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1008 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1014 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1020 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1026 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1032 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1038 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1044 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1050 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1056 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1062 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1068 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1074 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1080 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1086 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1092 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1098 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1104 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1110 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1116 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1122 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1128 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1134 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1140 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1146 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1152 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1158 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1164 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1170 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1176 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1182 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1188 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1194 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1200 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1206 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1212 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1218 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1224 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1230 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1236 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1242 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1248 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1254 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1260 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1266 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1272 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1278 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1284 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1290 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1296 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1302 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1308 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1314 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1320 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1326 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1332 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1338 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1344 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1350 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1356 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1362 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1368 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1374 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1380 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1386 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1392 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1398 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1404 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1410 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1416 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1422 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1428 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1434 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1440 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1446 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1452 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1458 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1464 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1470 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1476 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1482 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1488 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1494 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1500 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1506 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1512 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1518 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1524 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1530 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1536 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1542 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1548 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1554 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1560 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1566 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1572 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1578 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1584 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1590 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1596 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1602 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1608 --device cuda:0
python3 performance_large/generate_full_hf_model_outputs.py --model_id 1614 --device cuda:0