python3 performance_large/generate_hf_model_outputs.py --model_id 6 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 18 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 30 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 42 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 54 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 66 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 78 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 90 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 102 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 114 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 126 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 138 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 150 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 162 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 174 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 186 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 198 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 210 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 222 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 234 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 246 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 258 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 270 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 282 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 294 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 306 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 318 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 330 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 342 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 354 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 366 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 378 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 390 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 402 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 414 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 426 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 438 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 450 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 462 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 474 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 486 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 498 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 510 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 522 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 534 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 546 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 558 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 570 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 582 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 594 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 606 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 618 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 630 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 642 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 654 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 666 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 678 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 690 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 702 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 714 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 726 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 738 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 750 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 762 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 774 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 786 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 798 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 810 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 822 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 834 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 846 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 858 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 870 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 882 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 894 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 906 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 918 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 930 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 942 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 954 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 966 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 978 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 990 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1002 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1014 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1026 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1038 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1050 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1062 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1074 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1086 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1098 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1110 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1122 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1134 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1146 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1158 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1170 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1182 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1194 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1206 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1218 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1230 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1242 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1254 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1266 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1278 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1290 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1302 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1314 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1326 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1338 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1350 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1362 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1374 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1386 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1398 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1410 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1422 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1434 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1446 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1458 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1470 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1482 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1494 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1506 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1518 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1530 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1542 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1554 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1566 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1578 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1590 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1602 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1614 --device cuda:1