python3 performance_large/generate_hf_model_outputs.py --model_id 9 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 21 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 33 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 45 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 57 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 69 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 81 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 93 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 105 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 117 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 129 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 141 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 153 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 165 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 177 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 189 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 201 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 213 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 225 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 237 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 249 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 261 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 273 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 285 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 297 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 309 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 321 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 333 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 345 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 357 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 369 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 381 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 393 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 405 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 417 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 429 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 441 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 453 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 465 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 477 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 489 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 501 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 513 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 525 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 537 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 549 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 561 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 573 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 585 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 597 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 609 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 621 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 633 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 645 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 657 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 669 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 681 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 693 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 705 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 717 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 729 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 741 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 753 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 765 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 777 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 789 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 801 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 813 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 825 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 837 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 849 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 861 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 873 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 885 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 897 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 909 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 921 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 933 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 945 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 957 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 969 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 981 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 993 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1005 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1017 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1029 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1041 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1053 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1065 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1077 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1089 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1101 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1113 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1125 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1137 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1149 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1161 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1173 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1185 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1197 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1209 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1221 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1233 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1245 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1257 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1269 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1281 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1293 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1305 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1317 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1329 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1341 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1353 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1365 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1377 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1389 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1401 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1413 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1425 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1437 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1449 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1461 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1473 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1485 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1497 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1509 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1521 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1533 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1545 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1557 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1569 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1581 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1593 --device cuda:2
python3 performance_large/generate_hf_model_outputs.py --model_id 1605 --device cuda:2