python3 performance_large/generate_hf_model_outputs.py --model_id 5 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 17 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 29 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 41 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 53 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 65 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 77 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 89 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 101 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 113 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 125 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 137 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 149 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 161 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 173 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 185 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 197 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 209 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 221 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 233 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 245 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 257 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 269 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 281 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 293 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 305 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 317 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 329 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 341 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 353 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 365 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 377 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 389 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 401 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 413 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 425 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 437 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 449 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 461 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 473 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 485 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 497 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 509 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 521 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 533 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 545 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 557 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 569 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 581 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 593 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 605 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 617 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 629 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 641 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 653 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 665 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 677 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 689 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 701 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 713 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 725 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 737 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 749 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 761 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 773 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 785 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 797 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 809 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 821 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 833 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 845 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 857 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 869 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 881 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 893 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 905 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 917 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 929 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 941 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 953 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 965 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 977 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 989 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1001 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1013 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1025 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1037 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1049 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1061 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1073 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1085 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1097 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1109 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1121 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1133 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1145 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1157 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1169 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1181 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1193 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1205 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1217 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1229 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1241 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1253 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1265 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1277 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1289 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1301 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1313 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1325 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1337 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1349 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1361 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1373 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1385 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1397 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1409 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1421 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1433 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1445 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1457 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1469 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1481 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1493 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1505 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1517 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1529 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1541 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1553 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1565 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1577 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1589 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1601 --device cuda:1
python3 performance_large/generate_hf_model_outputs.py --model_id 1613 --device cuda:1